title: Web Development Documentation
description: Web Development Starter Kit for the 2024 Triton Hackathon hosted by CS Foreach @ UCSD.
theme: just-the-docs

url: https://kevshin2002.github.io/thwebdev/Home

aux_links:
  CS Foreach: https://www.csforeach.org/
