title: Web Development Starter Kit
description: This is the starter kit for those who want to learn about web development and how we can create websites!. This is your roadmap to explore the introductory concepts, going from top to bottom. Use the sections below to dive in and start your coding adventure!
theme: just-the-docs

url: https://kevshin2002.github.io/thwebdev

aux_links:
  CS Foreach: https://www.csforeach.org/
